export const items = [
    {
        type: "text",
        label: "Owner Name",
        name: "ownerName",
        view: ["viewer", "member", "qualified", "hc", "company", 'admin'],
        filter: [],
    },
    {
        type: "number",
        label: "Age",
        name: "age",
        view: ["viewer", "member", "qualified", "hc", "company", 'admin'],
        filter: [],
    },
    {
        type: "email",
        label: "Email",
        name: "email",
        view: ["viewer", "member", "qualified", "hc", "company", 'admin'],
        filter: [],
    },
    {
        type: "text",
        label: "Number",
        name: "number",
        view: ["viewer", "member", "qualified", "hc", "company", 'admin'],
        filter: [],
    },
    {
        type: "number",
        label: "No. of Staff",
        name: "noOfStaff",
        view: ["qualified", "hc", "company", 'admin'],
        filter: ["qualified", "hc", "company", 'admin'],
    },
    {
        type: "number",
        label: "No. of Shareholders",
        name: "noOfShareholders",
        view: ["qualified", "hc", "company", 'admin'],
        filter: ["qualified", "hc", "company", 'admin'],
    },
    {
        type: "select",
        label: "Property",
        values: ["Leasehold", "Freehold", "Relocatable", "Accomodation Included"],
        name: "relocatable",
        view: ["member", "qualified", "hc", "company", 'admin'],
        filter: ["qualified", "hc", "company", 'admin'],
    },
    {
        type: "select",
        label: "Owner Managed",
        values: ["Yes", "No"],
        name: "ownerManaged",
        view: ["qualified", "hc", "company", 'admin'],
        filter: ["qualified", "hc", "company", 'admin'],
    },
    {
        type: "select",
        label: "Reason For Selling",
        values: ["Illness/Health", "Another venture", "Part of the plan"],
        name: "reasonForSelling",
        view: ["qualified", "hc", "company", 'admin'],
        filter: ["qualified", "hc", "company", 'admin'],
    },
    {
        type: "textArea",
        label: "Services",
        name: "services",
        view: ["member", "qualified", "hc", "company", 'admin'],
        filter: [],
    },
    {
        type: "textArea",
        label: "Description",
        name: "description",
        view: ["member", "qualified", "hc", "company", 'admin'],
        filter: [],
    },
    {
        type: "datePicker",
        label: "Date added",
        name: "dateAdded",
        view: ["qualified", "hc", "company", 'admin'],
        filter: ["qualified", "hc", "company", 'admin'],
    },
    {
        type: "text",
        label: "Reference",
        name: "reference",
        view: ["viewer", "member", "qualified", "hc", "company", 'admin'],
        filter: ["viewer", "member", "qualified", "hc", "company", 'admin'],
    },
    {
        type: "select",
        label: "Industry",
        name: "industry",
        values: [
            `Agriculture, Horticulture & Marine`,
            `Bed & Breakfast, GuestHouse & Hotel`,
            `Building & Construction`,
            `Car, Motor & Transport`,
            `Care`,
            `Coaching, Education & Training`,
            `Commercial Property`,
            `Convenience, Newsagent & Post Office`,
            `Engineering & Manufacturing`,
            `Entertainment & Leisure`,
            `Financial & Professional`,
            `Food & Catering`,
            `Franchise Resale`,
            `Health & Beauty`,
            `Licensed & Public House`,
            `Media & Technology`,
            `Retail & Shop`,
            `Service`,
        ],
        view: ["viewer", "member", "qualified", "hc", "company", 'admin'],
        filter: ["viewer", "member", "qualified", "hc", "company", 'admin'],
    },
    {
        type: "datePicker",
        label: "Year Established",
        name: "yearEstablished",
        view: ["member", "qualified", "hc", "company", 'admin'],
        filter: ["qualified", "hc", "company", 'admin'],
    },
    {
        type: "text",
        label: "Name of business",
        name: "nameOfBusiness",
        view: ["viewer", "member", "qualified", "hc", "company", 'admin'],
        filter: [],
    },
    { type: "text", label: "Title", name: "title", view: ["viewer", "member", "qualified", "hc", "company", 'admin'], filter: [] },
    {
        type: "currency",
        label: "Current Debts",
        name: "currentDebts",
        view: ["qualified", "hc", "company", 'admin'],
        filter: ["qualified", "hc", "company", 'admin'],
    },
    {
        type: "currency",
        label: "Projected Annual Profit",
        name: "projectedAnnualProfit",
        view: ["viewer", "member", "qualified", "hc", "company", 'admin'],
        filter: ["viewer", "member", "qualified", "hc", "company", 'admin'],
    },
    {
        type: "currency",
        label: "Last Annual Profit",
        name: "lastAnnualProfit",
        view: ["member", "qualified", "hc", "company", 'admin'],
        filter: ["qualified", "hc", "company", 'admin'],
    },
    {
        type: "currency",
        label: "Projected Annual Turnover",
        name: "projectedAnnualTurnover",
        view: ["viewer", "member", "qualified", "hc", "company", 'admin'],
        filter: ["viewer", "member", "qualified", "hc", "company", 'admin'],
    },
    {
        type: "currency",
        label: "Last Annual Turnover",
        name: "lastAnnualTurnover",
        view: ["member", "qualified", "hc", "company", 'admin'],
        filter: ["qualified", "hc", "company", 'admin'],
    },
    {
        type: "currency",
        label: "Asking Price",
        name: "askingPrice",
        view: ["qualified", "hc", "company", 'admin'],
        filter: ["qualified", "hc", "company", 'admin'],
    },
];